# Generated by Django 6.0.2 on 2026-03-21 09:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='company_identifier',
            field=models.CharField(blank=True, help_text='3 à 50 caractères. Lettres, chiffres et tirets uniquement. Ex: braincorp-2026', max_length=50, null=True, unique=True, validators=[django.core.validators.MinLengthValidator(3, message="L'identifiant doit contenir au moins 3 caractères."), django.core.validators.RegexValidator(message="L'identifiant ne peut contenir que des lettres, chiffres et tirets (-). Pas d'espaces.", regex='^[a-zA-Z0-9\\-]+$')]),
        ),
    ]
