# Generated by Django 6.0.2 on 2026-03-31 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_company_identifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='legal_representative',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='customuser',
            name='review_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='siret',
            field=models.CharField(blank=True, max_length=14),
        ),
        migrations.AddField(
            model_name='customuser',
            name='verification_document',
            field=models.FileField(blank=True, null=True, upload_to='verification_docs/'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='verification_source',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='customuser',
            name='verification_status',
            field=models.CharField(choices=[('PENDING', 'En attente'), ('VERIFIED', 'Vérifié'), ('REJECTED', 'Refusé'), ('NEEDS_REVIEW', 'Révision manuelle')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='customuser',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
