# Generated by Django 6.0.2 on 2026-03-21 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='status',
            field=models.CharField(choices=[('PENDING', 'En attente'), ('CONFIRMED', 'Confirmé'), ('REJECTED', 'Rejeté'), ('CANCELLED', 'Annulé'), ('WAITLIST', "Liste d'attente")], default='PENDING', max_length=20),
        ),
    ]
