# Generated by Django 6.0.2 on 2026-03-21 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0002_alter_registration_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='accessibility_needs',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='registration',
            name='company_comment',
            field=models.TextField(blank=True, default=''),
        ),
    ]
