# Generated by Django 6.0.2 on 2026-03-20 17:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tags', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('date_start', models.DateTimeField()),
                ('date_end', models.DateTimeField()),
                ('capacity', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('DRAFT', 'Brouillon'), ('PUBLISHED', 'Publié'), ('CANCELLED', 'Annulé')], default='DRAFT', max_length=20)),
                ('format', models.CharField(choices=[('ONSITE', 'Présentiel'), ('ONLINE', 'Distanciel'), ('HYBRID', 'Présentiel + Live')], default='ONSITE', max_length=10)),
                ('registration_mode', models.CharField(choices=[('AUTO', 'Inscription automatique'), ('VALIDATION', "Validation par l'entreprise")], default='AUTO', max_length=10)),
                ('address_full', models.CharField(blank=True, max_length=300)),
                ('address_city', models.CharField(blank=True, max_length=100)),
                ('address_country', models.CharField(blank=True, max_length=100)),
                ('address_visibility', models.CharField(blank=True, choices=[('FULL', 'Adresse complète'), ('PARTIAL', 'Ville et pays uniquement')], default='FULL', max_length=10)),
                ('address_reveal_date', models.DateTimeField(blank=True, help_text="Si renseigné, l'adresse complète sera révélée à cette date", null=True)),
                ('online_platform', models.CharField(blank=True, help_text='ex: Zoom, YouTube, Teams', max_length=100)),
                ('online_link', models.URLField(blank=True)),
                ('online_visibility', models.CharField(blank=True, choices=[('FULL', 'Lien complet'), ('PARTIAL', 'Nom de la plateforme uniquement')], default='FULL', max_length=10)),
                ('online_reveal_date', models.DateTimeField(blank=True, help_text='Si renseigné, le lien complet sera révélé à cette date', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(blank=True, related_name='events', to='tags.tag')),
            ],
            options={
                'verbose_name': 'Événement',
                'verbose_name_plural': 'Événements',
                'ordering': ['date_start'],
            },
        ),
    ]
