# Generated by Django 6.0.2 on 2026-03-21 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='registration_deadline',
            field=models.DateTimeField(blank=True, help_text="Date limite d'inscription. Si vide, les inscriptions sont ouvertes jusqu'au début de l'event.", null=True),
        ),
    ]
