# Generated by Django 6.0.2 on 2026-03-21 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_registration_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='banner',
            field=models.ImageField(blank=True, help_text="Image/bannière de l'événement (format recommandé : 1200x400)", null=True, upload_to='banners/'),
        ),
    ]
